services:

  db:
    image: postgres:13.22-alpine3.21
    restart: always
    # set shared memory limit
    shm_size: 128mb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: changepassword
      POSTGRES_DB: user_service
    ports:
      - '5432:5432'